### ISSUE TITLE
Build fails on tests

### ISSUE THREAD

**Issue by panesofglass** [forki/NaturalSpec#2]
When running build.bat, the project is built, but the test target fails:
...
Time Elapsed 00:00:03.10
Building project: .\src\test\Spec.Euler\Spec.Euler.fsproj
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  .\src\test\Spec.Euler\Spec.Euler.fsproj /target:Build /p:Configuration=Debug /p:OutputPath=".\test"\
Microsoft (R) Build Engine Version 4.0.30319.1
[Microsoft .NET Framework, Version 4.0.30319.1]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 6/20/2010 8:35:24 PM.
Project ".\src\test\Spec.Euler\Spec.Euler.fsproj" on node 1 (Build target(s)).
PrepareForBuild:
  Creating directory "obj\Debug\".
  Creating directory "bin\Debug\".
Project ".\src\test\Spec.Euler\Spec.Euler.fsproj" (1) is building ".\src\app\NaturalSpec\NaturalSpec.fsproj" (2) on node 1 (default targets).
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  NaturalSpec -> .\test\NaturalSpec.dll
Done Building Project ".\src\app\NaturalSpec\NaturalSpec.fsproj" (default targets).
CoreCompile:
  ......\tools\FSharp\fsc.exe -o:obj\Debug\Spec.Euler.dll -g --debug:full --noframework --define:DEBUG --define:TRACE
--doc:bin\Debug\Spec.Euler.XML --optimize- --tailcalls- -r:.\tools\FSharp\FSharp.Core.dll -r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll -r:.\test\NaturalSpec.dll -r:.\tools\Nunit\nunit.framework.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Core.dll" -r:"C:\Program Files (x86)\Microsoft Cloud Programmability\Reactive Extensions\v1.0.2521.0\Net35\System.CoreEx.dll" -r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll -r:"C:\Program Files (x86)\Microsoft Cloud Programmability\Reactive Extensions\v1.0.2521.0\Net35\System.Interactive.dll" -r:"C:\Program Files (x86)\Microsoft Cloud Programmability\Reactive Extensions\v1.0.2521.0\Net35\System.Reactive.dll"
-r:"C:\Program Files (x86)\Microsoft Cloud Programmability\Reactive Extensions\v1.0.2521.0\Net35\System.Threading.dll" -r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Xml.dll --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors Memoization.fs MathHelper.fs StringHelper.fs Problem1.fs Problem2.fs Problem3.fs Problem4.fs Problem5.fs Problem6.fs Problem7.fs Problem8.fs Problem9.fs Problem10.fs Problem11.fs Problem12.fs Problem13.fs Problem14.fs Problem15.fs Problem16.fs Problem17.fs Problem18.fs Problem19.fs Problem20.fs Problem21.fs Problem22.fs Problem23.fs Problem25.fs Problem26.fs Problem30.fs Problem31.fs Problem48.fs Problem52.fs Problem53.fs Problem59.fs Problem67.fs Problem77.fs

.\src\test\Spec.Euler\Problem19.fs(4,12): error FS1108: The type 'System.IObservable`1' is required here and is unavailable. You must add a reference to assembly 'System.Observable, Version=1.0.0.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. [.\src\test\Spec.Euler\Spec.Euler.fsproj]

.\src\test\Spec.Euler\Problem19.fs(13,30): error FS0039: The type 'DateTime' is not defined [.\src\test\Spec.Euler\Spec.Euler.fsproj]

.\src\test\Spec.Euler\Problem19.fs(13,57): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [.\src\test\Spec.Euler\Spec.Euler.fsproj]

.\src\test\Spec.Euler\Problem19.fs(18,31): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [.\src\test\Spec.Euler\Spec.Euler.fsproj]

.\src\test\Spec.Euler\Problem19.fs(18,45): error FS0039: The namespace or module 'DayOfWeek' is not defined [.\src\test\Spec.Euler\Spec.Euler.fsproj]

.\src\test\Spec.Euler\Problem19.fs(18,65): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [.\src\test\Spec.Euler\Spec.Euler.fsproj]
Done Building Project ".\src\test\Spec.Euler\Spec.Euler.fsproj" (Build target(s)) -- FAILED.

Build FAILED.

".\src\test\Spec.Euler\Spec.Euler.fsproj" (Build target) (1) ->
(CoreCompile target) ->
  .\src\test\Spec.Euler\Problem19.fs(4,12): error FS1108: The type 'System.IObservable`1' is required here and is unavailable. You must add a reference to assembly 'System.Observable, Version=1.0.0.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. [.\src\test\Spec.Euler\Spec.Euler.fsproj]
  .\src\test\Spec.Euler\Problem19.fs(13,30): error FS0039: The type 'DateTime' is not defined [.\src\test\Spec.Euler\Spec.Euler.fsproj]
  .\src\test\Spec.Euler\Problem19.fs(13,57): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [.\src\test\Spec.Euler\Spec.Euler.fsproj]
  .\src\test\Spec.Euler\Problem19.fs(18,31): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [.\src\test\Spec.Euler\Spec.Euler.fsproj]
  .\src\test\Spec.Euler\Problem19.fs(18,45): error FS0039: The namespace or module 'DayOfWeek' is not defined [.\src\test\Spec.Euler\Spec.Euler.fsproj]
  .\src\test\Spec.Euler\Problem19.fs(18,65): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [.\src\test\Spec.Euler\Spec.Euler.fsproj]

```
0 Warning(s)
6 Error(s)
```

Time Elapsed 00:00:04.85
Running build failed.
Error:
Building .\src\test\Spec.Euler\Spec.Euler.fsproj project failed.

---
## Build Time Report

Target     Duration

---

Clean      00:0Fak0:00.0196836
BuildApp   00:00:07.3118153
Total:     00:00:29.7322913
------------e.---Ta-r----ge---t-H--e-l--p-e--r-+--B-u--i-l--d-E--r-r--o-r--:- --S-t-o-p---p-e--d- --b-u--i-l
d! Error occured in target "BuildTest".
Message: Building C:\Users\ryan\dev\NaturalSpec\src\test\Spec.Euler\Spec.Euler.fsproj project failed.
   at Fake.TargetHelper.run@182.Invoke(BuildError exn)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
   at Fake.TargetHelper.run(String targetName)
   at Fake.TargetHelper.Run@211.Invoke(String targetName)
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\Users\ryan\dev\NaturalSpec\build.fsx:line 90
Stopped due to error
Press any key to continue . . .

**Comment by forki** [comment]
Hi,

Thanks for reportings this. I fixed this issue on the Mock branch and forgot to merge it down into master. Now I cherry-picked the fix. Please try again.

Regards,
  Steffen
